### ISSUE TITLE
Hello, does LightSeq support the deployment of Transformer-based ASR and TTS systems?

### ISSUE THREAD

**Issue by Alex-Songs** [bytedance/lightseq#11]
Hello, does LightSeq support the deployment of Transformer-based ASR and TTS systems?

**Comment by lileicc** [comment]
@Alex-Songs In principle, Yes!
But we do not have any Transformer based ASR or TTS model handy, you are welcome to try and let us know if you encounter any issue. 
Depending on how you implement your ASR model, it may require additional MFCC preprocessing module to extract audio features.

**Comment by Alex-Songs** [comment]
OK, thanks!
