### ISSUE TITLE
difference inference result between TransformerEncoder and standard BertEncoder ?

### ISSUE THREAD

**Issue by spurscoder** [bytedance/lightseq#112]
Hi, thanks for your attention.

I have met this problem as below.
- inference results A of BERT with `HuggingFace Transformers` (standard BertEncoder)
- inference results B of BERT with `LightSeq` (TransformerEncoder)
- There is a difference between A and B.
- Specifically, even the first encoder layer output is different with same input vector.
- I run BERT inference just like [BERT `run_ner.py`](https://github.com/bytedance/lightseq/blob/master/examples/training/huggingface/README.md) which is replace BertEncoder with TransformerEncoder.

And, I noticed that the explanation in [`README.md`](https://github.com/bytedance/lightseq/blob/master/examples/training/huggingface/README.md) as below.
> Currently, Lightseq use TransformerEncoder in Bert finetune task, and it has a few differences with BertEncoder, which will influence performance of acc or f1. We will support standard BertEncoder ASAP.

So, can you help me figure out the difference?
- Where is the difference? (in cuda kernel, or layer norm, or config, or activation func)?
- Moreover, why is it different?

> I want to speed up my bert model's inference time with your cool `LightSeq`, and the model has already been trained with `HuggingFace Transformers`

Thanks!

**Comment by Taka152** [comment]
Here are the differences.
|TransformerEncoder | BertEncoder|
|---|---|
|pre-norm|post-norm|
|relu|gelu|

And we're considering releasing Bert inference (purely c++ and CUDA) from huggingface next month, stay tuned if just want to do fast inferences on your trained models.
