### ISSUE TITLE
There is a problem in reproducing fairseq

### ISSUE THREAD

**Issue by KelleyYin** [bytedance/lightseq#120]
I ran the script `ls_fairseq_wmt14en2de.sh`, but I encountered an error：
```
subprocess.CalledProcessError: Command '['which', 'g++ -std=gnu++0x']' returned non-zero exit status 1.
```
Environments:
* Pytorch: 1.7.1 
* CUDA: 10.2
* Fairseq 0.10.2
* lightseq v2.0.2 (pip insatll lightseq)

**Comment by Taka152** [comment]
It seems g++ is missing, you can install it and try.

>

**Comment by Andrewlesson** [comment]
i have encountered  the same problem too , to installed g++  is not the solution.
