### ISSUE TITLE
How to convert model like BertForTokenClassification by huggingface transformer to pb format

### ISSUE THREAD

**Issue by cdhx** [bytedance/lightseq#131]
only saw how to convert BART，gpt2 

after search for some pkl to onnx to pd code, they all only have one input, but for the task that need attention mask or token_seq_id，i don't know how to convert

**Comment by troore** [comment]
Currently not easy: https://github.com/bytedance/lightseq/issues/111#issuecomment-884616906.

**Comment by cdhx** [comment]
thanks for your reply, i wonder where the difficult is from 

1. huggingface transformer Encapsulation pipeline? so I cannot use huggingface BERTforxxx，but only the BERT model

2. have more than one input? so i still can use use lightseq for the pipeline that attention mask is not necessary like BERTforSequenceClassifcation?

**Comment by Taka152** [comment]
Bert example in lightseq.inference should be released in August, I promise.

For now, you can check [here](https://github.com/bytedance/lightseq/blob/b1e946211081330b6f0b900b80dcbd2e758573df/examples/training/huggingface/README.md) use lightseq.training to speedup up Bert encoder.

The coming release in lightseq.inference includes more acceleration like embedding.

If I lie, you can come to Beijing and hit me.

**Comment by cdhx** [comment]
thank you for your efforts

looking forward to lightseq getting better and better！

**Comment by troore** [comment]
> Bert example in lightseq.inference should be released in August, I promise.
> 
> For now, you can check [here](https://github.com/bytedance/lightseq/blob/b1e946211081330b6f0b900b80dcbd2e758573df/examples/training/huggingface/README.md) use lightseq.training to speedup up Bert encoder.
> 
> The coming release in lightseq.inference includes more acceleration like embedding.
> 
> If I lie, you can come to Beijing and hit me.

Haha, open source itself is not easy and should be appreciated by everyone. No matter the new feature will be released or not, we should be grateful for your excellent work!
