### ISSUE TITLE
AttributeError: module 'lightseq' has no attribute 'Transformer'

### ISSUE THREAD

**Issue by cdhx** [bytedance/lightseq#132]
```model_light = lightseq.Transformer('../../model/conjunction.pb',2)```

got error

```AttributeError: module 'lightseq' has no attribute 'Transformer'```

**Comment by cdhx** [comment]
follow this blog

https://godweiyang.com/2021/04/13/lightseq-python-usage/

**Comment by cdhx** [comment]
tried this
```
import lightseq.inference as lsi
import numpy as np

test_input = np.array([[5001, 2, 36, 5002]])
transformer = lsi.Transformer("transformer.pb", 32) # 32 is max batch size, it will decide GPU memory occupancy.
result = transformer.infer(test_input)
```

also failed
```
Parsing protobuf: ../../model/conjunction.pb
Traceback (most recent call last):
  File "<input>", line 4, in <module>
RuntimeError: Parse weights from [transformer.pb] failed.
```

my model is BertforTokenClassification by huggingface transformer

**Comment by troore** [comment]
> model_light = lightseq.Transformer('../../model/conjunction.pb',2)
> 
> got error
> 
> AttributeError: module 'lightseq' has no attribute 'Transformer'

I've also encountered this issue before. Two possible reasons:
1. If you installed through pip, check if the pip you used to execute the command `pip install lightseq` and the pip in your current environment are the same pip;
2. If you built and installed [from source](https://github.com/bytedance/lightseq/blob/master/docs/inference/build.md), make sure the commands are correctly executed.

**Comment by cdhx** [comment]
thanks for your advice

i used exactly the command ```pip install lightseq```, but i don't know what you means by "pip in your current environment are the same pip "

**Comment by troore** [comment]
> tried this
> 
> ```
> import lightseq.inference as lsi
> import numpy as np
> 
> test_input = np.array([[5001, 2, 36, 5002]])
> transformer = lsi.Transformer("transformer.pb", 32) # 32 is max batch size, it will decide GPU memory occupancy.
> result = transformer.infer(test_input)
> ```
> 
> also failed
> 
> ```
> Parsing protobuf: ../../model/conjunction.pb
> Traceback (most recent call last):
>   File "<input>", line 4, in <module>
> RuntimeError: Parse weights from [transformer.pb] failed.
> ```
> 
> my model is BertforTokenClassification by huggingface transformer
> 
> i install lightseq on Linux by pypi and the version is 2.1.0

Refer to [issue#111](https://github.com/bytedance/lightseq/issues/111), this is caused by incompatible pypi versions, or imcompatible cuda versions between binary LightSeq and your environment. Firstly try to checkout the latest tag, if it still doesn't work, try [build from source](https://github.com/bytedance/lightseq/blob/master/docs/inference/build.md)

**Comment by troore** [comment]
> thanks for your advice
> 
> i used exactly the command `pip install lightseq`, but i don't know what you means by "the pip in your current environment are the same pip "

I mean there may exist different versions of python or pip in your environment. Make sure you use the same version to install and run LightSeq.
