### ISSUE TITLE
not able to run the gptlm_example.cu.cc given in the model directory

### ISSUE THREAD

**Issue by rkoystart** [bytedance/lightseq#14]
I wanted to run the gptlm_example.cu.cc in the model directory. As far i know to run the gptlm_example.cu.cc, we need two file 1) gpt.pb 2)test_case.
please correct me if i have understood wrong about the above one.

when i run the following command:
`rkoy@rkoy:lightseq/lightseq/example$ g++ gptlm_example.cu.cc gpt.pb test_case `
i get the following error:
```
In file included from /usr/include/cublas_v2.h:65:0,
                 from lightseq/lightseq/model/gpt_encoder.h:3,
                 from gptlm_example.cu.cc:3:
/usr/include/cublas_api.h:72:10: fatal error: driver_types.h: No such file or directory
 #include "driver_types.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.

```
please let me know how i should resolve this

I am able to run the below command without any error
`rkoy@rkoy:lightseq$ ./v1.0.0_libs/gptlm_example.fp32 ./v0.0.1_gptlm.pkg/gpt.pb ./v0.0.1_gptlm.pkg/test_case                    `

I think the first and second command has the same functionality almost. Let me know if i have got anything wrong.
Thanks in advance!!!!!

**Comment by neopro12** [comment]
Due to the complex compilation dependencies, to build the gpt example from source code, you can follow the documentation here: https://github.com/bytedance/lightseq/blob/master/docs/build.md.
