### ISSUE TITLE
ls_bert运行报错

### ISSUE THREAD

**Issue by js19950726** [bytedance/lightseq#148]
我安装了lightseq==2.1.1

但是运行时
![image](https://user-images.githubusercontent.com/44122112/128815532-f5e5e19e-5d34-414e-b7a9-5c6948c26186.png)

找了半天bert在哪也没找到，可以告诉我咋解决吗，还是我少了什么步骤

**Comment by js19950726** [comment]
能不能贴一个运行流程？

**Comment by Taka152** [comment]
The pypi version hasn't update Bert support, you can build from source and try.
I'll try to release a new pypi version these days.

**Comment by js19950726** [comment]
我就是从源代码python setup.py install的啊
pypi上的版本不是2.1.0嘛
我的是2.1.1

**Comment by Taka152** [comment]
`pip install` only install training module. https://github.com/bytedance/lightseq/blob/a57966ae05f4801127ce45b0b432cfdc8fb38d96/setup.py#L130-L139
Check [here](https://github.com/bytedance/lightseq/blob/master/docs/inference/build.md) to install inference env and run `python setup.py install` again.

**Comment by Taka152** [comment]
A new version has been released on pypi, you can try `pip install lightseq` and run the bert example.

**Comment by godweiyang** [comment]
> 我就是从源代码python setup.py install的啊
> pypi上的版本不是2.1.0嘛
> 我的是2.1.1

We have updated the pypi version to 2.1.2. which includes the BERT inference. You can try again.

**Comment by zhentaoCoding** [comment]
我也遇到了这个问题，pypi version to 2.1.2也会报错

**Comment by Taka152** [comment]
2.1.2 works for me, could you share the error log?

**Comment by zhentaoCoding** [comment]
> 2.1.2 works for me, could you share the error log?

AttributeError: module 'lightseq.inference' has no attribute 'Bert'

**Comment by Taka152** [comment]
could you share the pip list version and your terminal screeshot

**Comment by zhentaoCoding** [comment]
> could you share the pip list version and your terminal screeshot

![image](https://user-images.githubusercontent.com/5669444/128973926-a220e5ea-83b7-4001-ad3c-1407f3006338.png)

**Comment by zhentaoCoding** [comment]
> could you share the pip list version and your terminal screeshot

__version__ = "2.1.2"

**Comment by Taka152** [comment]
Just want to make sure your `pwd`, this error may due to wrong package import, you can try running in different working directory

**Comment by zhentaoCoding** [comment]
pwd is correct

**Comment by godweiyang** [comment]
I try it successfully:
```text
<Trial 3417505 worker_0> tiger $ pip3 install lightseq
Defaulting to user installation because normal site-packages is not writeable
Collecting lightseq
  Downloading lightseq-2.1.2-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (40.8 MB)
     |████████████████████████████████| 40.8 MB 106 kB/s 
Requirement already satisfied: ninja in /usr/local/lib/python3.7/dist-packages (from lightseq) (1.10.2)
Installing collected packages: lightseq
Successfully installed lightseq-2.1.2
<Trial 3417505 worker_0> tiger $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightseq.inference as lsi
>>> lsi.Bert
<class 'lightseq.inference.Bert'>
```

**Comment by js19950726** [comment]
> > 2.1.2 works for me, could you share the error log?
> 
> AttributeError: module 'lightseq.inference' has no attribute 'Bert'

你这个问题是因为里面有个叫lightseq的文件夹，你import的是文件夹而不是你安装的lightseq库，你可以在gpu上把lightseq文件夹删除就好了

**Comment by godweiyang** [comment]
> > > 2.1.2 works for me, could you share the error log?
> > 
> > 
> > AttributeError: module 'lightseq.inference' has no attribute 'Bert'
> 
> 你这个问题是因为里面有个叫lightseq的文件夹，你import的是文件夹而不是你安装的lightseq库，你可以在gpu上把lightseq文件夹删除就好了

Another reason is that he directly clones and uses `pip install -e .` to install the source code, which will only install the training library for lack of inference environment. So we recommend installing by PyPi using `pip install lightseq`.
