### ISSUE TITLE
求问 lightseq 如何加载 pytorch 预训练模型，使得二者在相同输入的情况下输出完全相同？

### ISSUE THREAD

**Issue by real-zhangzhe** [bytedance/lightseq#150]
求问 lightseq 如何加载 pytorch 预训练模型，使得二者在相同输入的情况下输出完全相同？

经测试发现，lightseq transformer_encoder_layer load pytorch 预训练模型的参数后，相同输入下，二者的输出的余弦相似度只有约 91%，求问是我加载参数的方式有哪里不对吗？

最小复现代码集如下：

```python
import torch
import numpy as np
from lightseq.training.ops.pytorch.transformer_encoder_layer import (
    LSTransformerEncoderLayer,
)

torch.manual_seed(100)
dvs = torch.device("cuda:0")

encoder = torch.nn.TransformerEncoderLayer(
    d_model=512, nhead=4, dropout=0, dim_feedforward=1024
)
encoder = encoder.to(dvs)
encoder.eval()

src = torch.randn(10, 32, 512).to(dvs)
padding_mask = torch.randn(32, 10).to(dvs)

with torch.no_grad():
    t_out = encoder(src, src_key_padding_mask=padding_mask)
print(t_out.abs().sum().item())

config = LSTransformerEncoderLayer.get_config(
    hidden_size=512,
    nhead=4,
    attn_prob_dropout_ratio=0,
    activation_dropout_ratio=0,
    hidden_dropout_ratio=0,
    intermediate_size=1024,
    fp16=False,
    max_batch_tokens=320,
    max_seq_len=32,
    local_rank=0,
    pre_layer_norm=False,
)


def get_enc_layer_params(layer):
    init_ws = []
    init_bs = []
    k_weight, q_weight, v_weight = (
        layer.self_attn.in_proj_weight.detach().clone().split(512, 0)
    )
    k_bias, q_bias, v_bias = layer.self_attn.in_proj_bias.detach().clone().split(512, 0)

    init_ws.append(k_weight)
    init_bs.append(k_bias)
    init_ws.append(q_weight)
    init_bs.append(q_bias)
    init_ws.append(v_weight)
    init_bs.append(v_bias)
    init_ws.append(layer.self_attn.out_proj.weight.detach().clone())
    init_bs.append(layer.self_attn.out_proj.bias.detach().clone())
    init_ws.append(layer.norm1.weight.detach().clone())
    init_bs.append(layer.norm1.bias.detach().clone())
    init_ws.append(layer.linear1.weight.detach().clone())
    init_bs.append(layer.linear1.bias.detach().clone())
    init_ws.append(layer.linear2.weight.detach().clone())
    init_bs.append(layer.linear2.bias.detach().clone())
    init_ws.append(layer.norm2.weight.detach().clone())
    init_bs.append(layer.norm2.bias.detach().clone())

    return init_ws, init_bs


padding_mask = padding_mask.to(dvs)
initial_weights, initial_biases = get_enc_layer_params(encoder)
ls_encoder = LSTransformerEncoderLayer(config, initial_weights, initial_biases)
ls_encoder = ls_encoder.to(dvs)
ls_encoder.eval()
with torch.no_grad():
    ls_out = ls_encoder(src, encoder_padding_mask=padding_mask / -10000.0)
print(ls_out.abs().sum().item())


def cosine_similarity(x, y):
    num = x.dot(y.T)
    denom = np.linalg.norm(x) * np.linalg.norm(y)
    return num / denom


result = cosine_similarity(
    t_out.detach().cpu().numpy().reshape(-1), ls_out.detach().cpu().numpy().reshape(-1)
)
print("cosine_similarity = ", result)
```

求解答，谢谢🙏

**Comment by godweiyang** [comment]
> 求问 lightseq 如何加载 pytorch 预训练模型，使得二者在相同输入的情况下输出完全相同？
> 
> 经测试发现，lightseq transformer_encoder_layer load pytorch 预训练模型的参数后，相同输入下，二者的输出的余弦相似度只有约 91%，求问是我加载参数的方式有哪里不对吗？
> 
> 最小复现代码集如下：
> 
> ```python
> import torch
> import numpy as np
> from lightseq.training.ops.pytorch.transformer_encoder_layer import (
>     LSTransformerEncoderLayer,
> )
> 
> torch.manual_seed(100)
> dvs = torch.device("cuda:0")
> 
> encoder = torch.nn.TransformerEncoderLayer(
>     d_model=512, nhead=4, dropout=0, dim_feedforward=1024
> )
> encoder = encoder.to(dvs)
> encoder.eval()
> 
> src = torch.randn(10, 32, 512).to(dvs)
> padding_mask = torch.randn(32, 10).to(dvs)
> 
> with torch.no_grad():
>     t_out = encoder(src, src_key_padding_mask=padding_mask)
> print(t_out.abs().sum().item())
> 
> config = LSTransformerEncoderLayer.get_config(
>     hidden_size=512,
>     nhead=4,
>     attn_prob_dropout_ratio=0,
>     activation_dropout_ratio=0,
>     hidden_dropout_ratio=0,
>     intermediate_size=1024,
>     fp16=False,
>     max_batch_tokens=320,
>     max_seq_len=32,
>     local_rank=0,
>     pre_layer_norm=False,
> )
> 
> 
> def get_enc_layer_params(layer):
>     init_ws = []
>     init_bs = []
>     k_weight, q_weight, v_weight = (
>         layer.self_attn.in_proj_weight.detach().clone().split(512, 0)
>     )
>     k_bias, q_bias, v_bias = layer.self_attn.in_proj_bias.detach().clone().split(512, 0)
> 
>     init_ws.append(k_weight)
>     init_bs.append(k_bias)
>     init_ws.append(q_weight)
>     init_bs.append(q_bias)
>     init_ws.append(v_weight)
>     init_bs.append(v_bias)
>     init_ws.append(layer.self_attn.out_proj.weight.detach().clone())
>     init_bs.append(layer.self_attn.out_proj.bias.detach().clone())
>     init_ws.append(layer.norm1.weight.detach().clone())
>     init_bs.append(layer.norm1.bias.detach().clone())
>     init_ws.append(layer.linear1.weight.detach().clone())
>     init_bs.append(layer.linear1.bias.detach().clone())
>     init_ws.append(layer.linear2.weight.detach().clone())
>     init_bs.append(layer.linear2.bias.detach().clone())
>     init_ws.append(layer.norm2.weight.detach().clone())
>     init_bs.append(layer.norm2.bias.detach().clone())
> 
>     return init_ws, init_bs
> 
> 
> padding_mask = padding_mask.to(dvs)
> initial_weights, initial_biases = get_enc_layer_params(encoder)
> ls_encoder = LSTransformerEncoderLayer(config, initial_weights, initial_biases)
> ls_encoder = ls_encoder.to(dvs)
> ls_encoder.eval()
> with torch.no_grad():
>     ls_out = ls_encoder(src, encoder_padding_mask=padding_mask / -10000.0)
> print(ls_out.abs().sum().item())
> 
> 
> def cosine_similarity(x, y):
>     num = x.dot(y.T)
>     denom = np.linalg.norm(x) * np.linalg.norm(y)
>     return num / denom
> 
> 
> result = cosine_similarity(
>     t_out.detach().cpu().numpy().reshape(-1), ls_out.detach().cpu().numpy().reshape(-1)
> )
> print("cosine_similarity = ", result)
> ```
> 
> 求解答，谢谢🙏

Thanks for your attention to LightSeq!

You have two tiny errors:
1. `padding_mask` should only have 1 in the end of one sentence.
2. The input shape of LightSeq encoder layer should be `(seq_len, batch_size, hidden_dim)`.

I slightly modify your code and you can run it~

```python
import random
import torch
import numpy as np
from lightseq.training import LSTransformerEncoderLayer

seed = 666
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

bsz = 32
sl = 50
hidden_dim = 512
nhead = 4
dvs = torch.device("cuda:0")
src = torch.randn((bsz, sl, hidden_dim), dtype=torch.float, device=dvs)
padding_mask = torch.zeros((bsz, sl), device=dvs)
for b in range(bsz):
    valid_seq_len = random.randint(1, sl)
    padding_mask[b, valid_seq_len:] = 1
padding_mask = padding_mask.to(dtype=torch.bool)

encoder = torch.nn.TransformerEncoderLayer(
    d_model=hidden_dim, nhead=nhead, dropout=0, dim_feedforward=hidden_dim*4
)
encoder = encoder.to(dtype=torch.float, device=dvs)
t_out = encoder(src.transpose(0, 1), src_key_padding_mask=padding_mask).transpose(0, 1)

config = LSTransformerEncoderLayer.get_config(
    hidden_size=hidden_dim,
    nhead=nhead,
    attn_prob_dropout_ratio=0,
    activation_dropout_ratio=0,
    hidden_dropout_ratio=0,
    intermediate_size=hidden_dim*4,
    fp16=False,
    max_batch_tokens=2000,
    max_seq_len=100,
    local_rank=0,
    pre_layer_norm=False,
)

def get_enc_layer_params(layer):
    init_ws = []
    init_bs = []
    q_weight, k_weight, v_weight = (
        layer.self_attn.in_proj_weight.detach().clone().split(hidden_dim, 0)
    )
    q_bias, k_bias, v_bias = layer.self_attn.in_proj_bias.detach().clone().split(hidden_dim, 0)

    init_ws.append(q_weight)
    init_bs.append(q_bias)
    init_ws.append(k_weight)
    init_bs.append(k_bias)
    init_ws.append(v_weight)
    init_bs.append(v_bias)
    init_ws.append(layer.self_attn.out_proj.weight.detach().clone())
    init_bs.append(layer.self_attn.out_proj.bias.detach().clone())
    init_ws.append(layer.norm1.weight.detach().clone())
    init_bs.append(layer.norm1.bias.detach().clone())
    init_ws.append(layer.linear1.weight.detach().clone())
    init_bs.append(layer.linear1.bias.detach().clone())
    init_ws.append(layer.linear2.weight.detach().clone())
    init_bs.append(layer.linear2.bias.detach().clone())
    init_ws.append(layer.norm2.weight.detach().clone())
    init_bs.append(layer.norm2.bias.detach().clone())

    return init_ws, init_bs

initial_weights, initial_biases = get_enc_layer_params(encoder)
ls_encoder = LSTransformerEncoderLayer(config, initial_weights, initial_biases)
ls_encoder = ls_encoder.to(dtype=torch.float, device=dvs)
ls_out = ls_encoder(src, encoder_padding_mask=padding_mask)

def cosine_similarity(x, y):
    num = x.dot(y.T)
    denom = np.linalg.norm(x) * np.linalg.norm(y)
    return num / denom

result = cosine_similarity(
    t_out.detach().cpu().numpy().reshape(-1), ls_out.detach().cpu().numpy().reshape(-1)
)

print("torch:   ", t_out.abs().sum().item())
print("lightseq:", ls_out.abs().sum().item())
print("cos_sim =", result)
print("allclose:", torch.allclose(t_out, ls_out, rtol=1e-2, atol=1e-2))
```
