### ISSUE TITLE
Question about compile options

### ISSUE THREAD

**Issue by smallv0221** [bytedance/lightseq#159]
I follow the Quick Start in Inference and used pip install lightseq to install this package. How can I know if i'm running in FP16 mode? Is there any perems to control it?

**Comment by Taka152** [comment]
the install from PyPI and default is fp16, fp32 running needs to compile from source. You can check [here](https://github.com/bytedance/lightseq/blob/4a0b1b03807992d992543420cff838750b163799/docs/inference/build.md)

**Comment by smallv0221** [comment]
Thanks！
