### ISSUE TITLE
Support for VIT-small (hidden_dim=384)

### ISSUE THREAD

**Issue by woskii** [bytedance/lightseq#163]
Hello, thank you for your contribution. 
I want to replace the encoders in vit-small with LSHFTransformerEncoderLayer. For each encoder, num_attention_heads = 6 and hidden_dim = 384. However, there is an error [here](https://github.com/bytedance/lightseq/blob/f0a9cc7f6ff44ef5db8d8d568805b5815fc85165/lightseq/training/ops/pytorch/transformer_encoder_layer.py#L268) says that hidden_dim must be an integer multiple of 256. 
Why does LSHFTransformerEncoderLayer have this restriction？ Is there any solution to use LSHFTransformerEncoderLayer in vit-small? 
Correct me if I am wrong. Thanks!

**Comment by woskii** [comment]
Thanks for the update. Is there any way that I can use the new code without building from source? @neopro12

**Comment by Taka152** [comment]
PyPI version has already been updated, check version 2.0.3.

**Comment by woskii** [comment]
Sorry but do you mean 2.1.3 [here](https://pypi.org/project/lightseq/#modal-close)? 
Still has the restriction in lightseq-2.1.3.tar.gz and the same as the wheel file.

> PyPI version has already been updated, check version 2.0.3.

**Comment by Taka152** [comment]
My mistake, this version doesn't include #164, install from source should be smooth without compiling

**Comment by Taka152** [comment]
You can check 2.1.3.post2, it includes the commit a5844a2

**Comment by woskii** [comment]
Thanks for the quick reply. The new PyPI version can work now.
