### ISSUE TITLE
请问下，如果编码部分是CNN，lightseq是否可以支持？应该如何进行模型转换和推理？

### ISSUE THREAD

**Issue by cjt222** [bytedance/lightseq#165]
模型是CNN+transformer encoder + transformer decoder 的结构，这种应该如何进行模型转换和推理加速？

**Comment by Taka152** [comment]
You can try TransformerDecoder to accelerate your inference. Follow the export of Bart to get pb file. When inference, use `lightseq.training.TransformerDecoder` to accept the output of encoder and accelerate decoder forward and searching.
