### ISSUE TITLE
Error in warp reduce sum

### ISSUE THREAD

**Issue by xin-w8023** [bytedance/lightseq#166]
https://github.com/bytedance/lightseq/blob/a5844a287f08f3190438b2bfbab15bf5c0eb525d/lightseq/training/csrc/kernels/includes/block_reduce.h#L35  
this line should be `val = (threadIdx.x < ((blockDim.x + 31) >> 5)) ? shared[lane] : (T)0.0f; ` to avoid error if `blockDim.x` cannot be divided by `1 >> 5`

**Comment by neopro12** [comment]
Yes, but blockDim.x should always be divided by 32(all thread in a warp should be active) when call block_reduce.
Because the activity of inactive thread is undefined in cuda when warp reduce.

**Comment by xin-w8023** [comment]
> Yes, but blockDim.x should always be divided by 32(all thread in a warp should be active) when call block_reduce.
> Because the activity of inactive thread is undefined in cuda when warp reduce.

all right, that makes sense.
