### ISSUE TITLE
pytorch GPT模型显存OOM，cuda11不能运行

### ISSUE THREAD

**Issue by bigprince97** [bytedance/lightseq#17]
感谢你们的开源工作，我用自己的模型转化之后可以成功用lightseq成功预测，加速效果的确明显，但是vocab size只能为非常小的值，一旦过大，就会爆显存，实例模型的vocab size是5004，有相应解决方案吗？在3090上也不能用Lightseq，有支持3090的打算吗？

**Comment by Taka152** [comment]
@bigprince97 感谢你使用lightseq并成功应用在自己的模型上面。回答一下你提出的两个问题：

1.vocab设置过大显存会爆。
显存占用除了vocab size会影响之外，max_batch_size和max_step的设置也会影响到显存的占用。建议可以适当调小这两个参数来提供更多的空间给更大的vocab size。

2.3090使用lightseq。
目前的使用并没有限制显卡的具体型号，只限制了cuda>=10.1，所以理论上是可以在3090上成功使用的。方便分享更多的信息以查看具体原因吗，包括报错，cuda版本等信息。

**Comment by bigprince97** [comment]
cuda版本是11.0
在创建容器时会提示tensorrt server的提示3090不支持该容器。
![image](https://user-images.githubusercontent.com/51944774/101852975-cb31b680-3b99-11eb-9d75-5b8cc2c536e9.png)
运行实例代码时，报错如下：
![image](https://user-images.githubusercontent.com/51944774/101853004-d84ea580-3b99-11eb-9bff-035c573e05e0.png)

**Comment by bigprince97** [comment]
max_batch_size和max_step两个参数在proto文件里没有，应该就是test case文件的第一行的那两个数据，我改成了1和6，使用1亿参数的gpt2模型，vocab size为10000都会爆显存，把层数减少一般，vocab size设为5000才能够正常进行预测。

**Comment by bigprince97** [comment]
另外我将pytorch版本的gpt2的参数根据proto转换成了对应的模型文件，可以正常推理，但是预测结果和pytorch版本的gpt2有很大差异，pytorch版本是按照gpt2论文的结构，可能和lightseq里面的gpt模型结构有细微差异，这一块具体的模型结构，能够麻烦提供具体的pytorch和tf版本的实现吗？

**Comment by bigprince97** [comment]
结果不一致的问题已经解决了，不是模型结构不一致的问题，是pytorch的参数矩阵转置问题。

**Comment by Taka152** [comment]
很高兴看到你的问题得到解决，剩下一个是3090上的运行。

我们前几天更新了CMake的编译方法，解决了对于Triton inference server镜像的依赖，欢迎你尝试一下doc/build.md里提到的方法进行编译，应该可以解决在3090或者说是cuda11下的运行问题。

**Comment by bigprince97** [comment]
编译的时候失败了，使用的cuda11环境。
![image](https://user-images.githubusercontent.com/51944774/102157056-c3d01d00-3eb9-11eb-8902-3dc4d23c3984.png)
![image](https://user-images.githubusercontent.com/51944774/102157069-cb8fc180-3eb9-11eb-84f2-2c2adea3edf2.png)
![image](https://user-images.githubusercontent.com/51944774/102157095-d77b8380-3eb9-11eb-9269-06fe9d8e9f6f.png)

**Comment by Majokiki** [comment]
> 结果不一致的问题已经解决了，不是模型结构不一致的问题，是pytorch的参数矩阵转置问题。
@bigprince97 您好，我也遇到了lightseq预测结果和pytorch版本的gpt2（https://github.com/yangjianxin1/GPT2-chitchat）不一致的问题，百思不解中幸运地找到了您的解释，请问您说的pytorch的参数矩阵转置的问题，是出现在torch.load()中的吗？能否给一些详细的信息呢？感谢

**Comment by Taka152** [comment]
> > 结果不一致的问题已经解决了，不是模型结构不一致的问题，是pytorch的参数矩阵转置问题。
> 
> @bigprince97 您好，我也遇到了lightseq预测结果和pytorch版本的gpt2（[https://github.com/yangjianxin1/GPT2-chitchat）](https://github.com/yangjianxin1/GPT2-chitchat%EF%BC%89)
> 不一致的问题，百思不解中幸运地找到了您的解释，请问您说的pytorch的参数矩阵转置的问题，是出现在torch.load()中的吗？能否给一些详细的信息呢？感谢

@Majokiki pytorch的weight很多都是[out_dim, in_dim]的方式存储的，lightseq中需要[in_dim, out_dim]的方式存储

**Comment by YINGPENGZH** [comment]
> > > 结果不一致的问题已经解决了，不是模型结构不一致的问题，是pytorch的参数矩阵转置问题。
> > 
> > 
> > @bigprince97 您好，我也遇到了lightseq预测结果和pytorch版本的gpt2（[https://github.com/yangjianxin1/GPT2-chitchat）](https://github.com/yangjianxin1/GPT2-chitchat%EF%BC%89)
> > 不一致的问题，百思不解中幸运地找到了您的解释，请问您说的pytorch的参数矩阵转置的问题，是出现在torch.load()中的吗？能否给一些详细的信息呢？感谢
> 
> @Majokiki pytorch的weight很多都是[out_dim, in_dim]的方式存储的，lightseq中需要[in_dim, out_dim]的方式存储

您好，我也遇到了pytorch和lightseq的gpt2不一致的问题，请问具体是怎么解决的呢？在pytorch模型转化之前做什么吗？
