### ISSUE TITLE
The perem of infer() not working

### ISSUE THREAD

**Issue by smallv0221** [bytedance/lightseq#171]
I follow the quick start of tranformer infer in readme. And I want to change beam_size for beam search. But inputing beam_size to infer() function don't work. 
![image](https://user-images.githubusercontent.com/33639025/132012314-96d1690b-e295-4974-a0e5-0106b6eebe6a.png)
The printed generate config says the beam_size is still 4.  And the second dim of output is 4 two.

**Comment by neopro12** [comment]
The "beam_size" argument in the infer() api is not work currently. You can set it in https://github.com/bytedance/lightseq/blob/master/lightseq/inference/proto/transformer.proto#L101 when you export your model to lightseq pb format.
