### ISSUE TITLE
Question about diverse_lambda in beam search

### ISSUE THREAD

**Issue by smallv0221** [bytedance/lightseq#175]
I see that lightseq support diverse beam search. But the actual implementation seems different from this paper https://arxiv.org/pdf/1610.02424.pdf. Is your diverse beam search a different strategy or an approximate implementation.

**Comment by Taka152** [comment]
Actually, We are implementing this paper https://arxiv.org/pdf/1611.08562.pdf

**Comment by Taka152** [comment]
Maybe it's better to call it [diverse_siblings_search](https://github.com/pytorch/fairseq/blob/e3fafbdfc9a39ba8339ebde98aa01c5349ab060d/fairseq/search.py#L745).

**Comment by smallv0221** [comment]
Is this the same diverse strategy as FasterTransformer?

**Comment by Taka152** [comment]
It seems like the same strategy according to the name

**Comment by smallv0221** [comment]
Thanks
