### ISSUE TITLE
每个token_id推理后获得12层encoder输出结果一摸一样

### ISSUE THREAD

**Issue by js19950726** [bytedance/lightseq#182]
我是用的keras训练的bert-base模型，然后将模型的参数通过hf_bert_export.py到出为hdf5文件。然后通过修改ls_bert.py文件来推理，但是获得的结果为
![image](https://user-images.githubusercontent.com/44122112/133739633-699fc7ea-b53c-4217-9068-4d27792d72b4.png)

这是我自己训练的模型参数
![image](https://user-images.githubusercontent.com/44122112/133739839-f829247c-f26e-4abb-a5c3-56eed7aed45e.png)

我想问一下，是我哪里出了问题，谢谢

**Comment by Taka152** [comment]
0 is for unmasked value, 1 is for masked value. You just mask all your input. :)

**Comment by Taka152** [comment]
could you try the mask with all zeros, it seems we provide the wrong mask in the example

**Comment by Taka152** [comment]
you can build debug version to check intermediate results of lightseq, and compare to keras results to debug
https://github.com/bytedance/lightseq/blob/master/docs/inference/build.md
