### ISSUE TITLE
any possible made lightseq slower than huggingface 【in inference `ls_bert`】 ?

### ISSUE THREAD

**Issue by nlp4whp** [bytedance/lightseq#184]
does anyone know any possible made lightseq slower than huggingface ?

case for me, `ls_bert.py` show `lightseq time 0.126s` but `huggingface time: 0.0185s`

btw  I don't install `fairseq` and `sacremoses` and 

torch                   1.8.0
transformers.     4.9.2
lightseq               2.1.4

**Comment by Taka152** [comment]
Perhaps your GPU is not good at fp16 inference, you can visit the Nvidia website to check your GPU performance. If so, you can try to build from the source to do fp32 inference.

**Comment by nlp4whp** [comment]
> Perhaps your GPU is not good at fp16 inference, you can visit the Nvidia website to check your GPU performance. If so, you can try to build from the source to do fp32 inference.

Thank you so much, but have you met this error in building `make -j` step (after cmake -DCMAKE_CUDA_COMPILER) ?

```
/home/wanghaipeng/Projects/onnxServer/lightseq/3rdparty/cub/cub/block/../iterator/../detail/device_synchronize.cuh:19:10: fatal error: cub/util_arch.cuh: No such file or directory
 #include <cub/util_arch.cuh>
```

**Comment by nlp4whp** [comment]
> Perhaps your GPU is not good at fp16 inference, you can visit the Nvidia website to check your GPU performance. If so, you can try to build from the source to do fp32 inference.

Thank you, and sorry to bother you again

in compiling, I got error `fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory`

due to root permission, I installed `protobuf` in my user home, and added config into `CMakeLists.txt`:

```
set(Protobuf_PREFIX_PATH
    "/home/xxx/library/protobuffers/include"            
    "/home/xxx/library/protobuffers/lib"             
    "/home/xxx/library/protobuffers/bin" )
list(APPEND CMAKE_PREFIX_PATH "${Protobuf_PREFIX_PATH}")
find_package(Protobuf REQUIRED)
```

how could I let compiler know where these header files is

**Comment by Taka152** [comment]
CMake path problem could be tricky, I suggest building in docker to solve
permission problem.
