### ISSUE TITLE
Can you provide a docker file that can test training and inference code the lightseq?

### ISSUE THREAD

**Issue by pdh930105** [bytedance/lightseq#186]
I tried to set up LightSeq on docker system (RTX2080TI 4-way or A100 2-way) but failed to set it for 8 hours. 

Therefore, please upload Dockerfile or Images using LightSeq system test.

(I tested based on image file nvcr.io/nvidia/pytorch:21.08, 20.12, 20.10, taka23/lightseq .. etc but didn't succeed.)

**Comment by Taka152** [comment]
Thanks for your advice, what error are you facing. I'm not sure if a Dockerfile could solve, because the GPU driver is not usually included in docker image

**Comment by pdh930105** [comment]
> Thanks for your advice, what error are you facing. I'm not sure if a Dockerfile could solve, because the GPU driver is not usually included in docker image

**Comment by pdh930105** [comment]
> Thanks for your advice, what error are you facing. I'm not sure if a Dockerfile could solve, because the GPU driver is not usually included in docker image

Then, can you explain details environment ex) CUDA version, nvidia driver, pytorch version ... etc for using lightseq?

I want to train deeplearning via lightseq because thus code is very simple and powerful performance

**Comment by Taka152** [comment]
Lightseq will build for your pytorch, that is if your pytorch works fine with your cuda and driver, lightseq will build with your env at runtime.
For example, we usually test lightseq using driver 450, cuda 11, and torch==1.7.1.

**Comment by pdh930105** [comment]
> If your pytorch works fine with your cuda and driver, lightseq will build with your env at runtime.
> For example, we usually test lightseq using driver 450, cuda 11, and torch==1.7.1.

Thanks. I will test this environment.

**Comment by VincentChen95** [comment]
hello @pdh930105  did you make any progress on this issue?
I tried a lot of combinations of torch/cuda/driver, but still get the issue to run the inference examples.
could you please share your configuration if you successed? thank you

**Comment by VincentChen95** [comment]
hello @Taka152 
could you please post your configurations when you test the lightseq? thank you

i tried cuda 10.1, 10.2, 11.1, 11.2, and keep getting this issue:

code:

```
import lightseq.inference as lsi
import numpy as np

test_input = np.array([[5001, 2, 36, 5002]])
transformer = lsi.Transformer("transformer.pb", 2) # 32 is max batch size, it will decide GPU memory occupancy.
result = transformer.infer(test_input)
```

log

```
Parsing protobuf: transformer.pb
Finish loading src_emb_wei from host to device
Finish loading trg_emb_wei from host to device
Finish loading enc_wei from host to device
Finish loading dec_wei from host to device
Finish loading all weight from host to device
***model config***
encoder layers: 8
decoder layers: 4
hidden size: 512
inner size: 2048
head number: 8
dim per head: 64
src vocab size: 5003
trg vocab size: 5003
is_post_ln: 0
no_scale_embedding: 0
use_gelu: 0
start_id: 5001
end_id: 5002
padding_id: 5003
is_multilingual: 0

***generator config***
beam size: 4
extra decode length(max decode length - src input length): 10
length penalty: 0.6
diverse lambda: 0
sampling method: beam_search
topk: 4
topp: 0.75
Allocated 9MB GPU buffer for transformer
decoder buffer init start
Traceback (most recent call last):
  File "infer.py", line 5, in <module>
    transformer = lsi.Transformer("transformer.pb", 2) # 32 is max batch size, it will decide GPU memory occupancy.
RuntimeError: [CUDA][ERROR] /tmp/build-via-sdist-lcobild4/lightseq-2.1.4/lightseq/inference/model/decoder.cc.cu(205): invalid device function

```
