### ISSUE TITLE
convert gpt model exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by BinaryUltra** [bytedance/lightseq#21]
![image](https://user-images.githubusercontent.com/21968860/104146890-4db2cd80-5407-11eb-9ba0-0328dde47bcf.png)

I encountered error when convert my own model to .pb format  which contain 32 encoder layers, how should I get solve the problem.

**Comment by Taka152** [comment]
We haven't supported any big model like GPT3 by now. I recommend finding Protobuf's alternative to solve the limitation of 2GB message size, the related sources are in the `proto` folder, It would be appreciated if you make a PR.
