### ISSUE TITLE
train gpt2 from scratch

### ISSUE THREAD

**Issue by YINGPENGZH** [bytedance/lightseq#212]
I want to train a gpt2 model from scratch without pretrain model by using lightseq. Is lightseq support?

**Comment by neopro12** [comment]
We have not yet provided an end-to-end training sample for gpt2. 
You can try is using our encoder layer https://github.com/bytedance/lightseq/blob/master/lightseq/training/ops/pytorch/transformer_decoder_layer.py
We will provide it in the near future.
