### ISSUE TITLE
Can lightseq gpt2  inference  with multi specific gpus ? How to set the device ids?

### ISSUE THREAD

**Issue by YINGPENGZH** [bytedance/lightseq#224]
The following code use gpu0 default, can I use other gpus? how to set the devices id like pytorch?
print("creating lightseq model...")
ls_model = lsi.Gpt("./gpt2_model.hdf5", max_batch_size=16)

**Comment by neopro12** [comment]
You can set the CUDA_VISIBLE_DEVICES env, e.g. CUDA_VISIBLE_DEVICES=1
https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

**Comment by YINGPENGZH** [comment]
> You can set the CUDA_VISIBLE_DEVICES env, e.g. CUDA_VISIBLE_DEVICES=1 https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

I set the device id 0,1, but the code is still run on GPU:0, are there any functions like pytorch's Dataparallel in lightseq?  My shell example is the following:

export CUDA_VISIBLE_DEVICES=0,1

python -u generate.py \
  --device '0,1' \
  --save_samples_path ./output \
  --raw_data_path ./data \
  --batch_size 128 \
  --max_batch_size 130 \
  --tokenizer_path cache/vocab.txt \
  --model_path pretrained_model/

**Comment by Taka152** [comment]
You can run generate.py for each of your GPU.

**Comment by neopro12** [comment]
try --device '1'
