### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'g++ -std=gnu++0x']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Andrewlesson** [bytedance/lightseq#227]
when i run the command : python lightseq/examples/training/custom/run.py , i got the problem below
there is no use to reinstall g++

![image](https://user-images.githubusercontent.com/10346684/142378370-b26f72a1-8587-4c0c-a2db-805a6232f718.png)

**Comment by Taka152** [comment]
It seems a problem in the torch extension, you can check the source of `cpp_extension.py` and find it out.

**Comment by Andrewlesson** [comment]
I think  it may be caused by the inconsistent relationship between the software versions. Can you give me a complete software version?  For example: pytorch， python， lightseq，fairseq，gcc,  cuda， Driver Version and so on

**Comment by Taka152** [comment]
Our test env is :
debian 10 
pytorch ==1.8
fairseq == 0.10.2
cuda 11.0
driver 450
