### ISSUE TITLE
RuntimeError: Error building extension 'lightseq_layers'

### ISSUE THREAD

**Issue by Andrewlesson** [bytedance/lightseq#228]
when i run command python ls_transformer_export.py or sh ls_fairseq_wmt14en2de.sh . i will get the runtimeErro below

![image](https://user-images.githubusercontent.com/10346684/142395452-b6707a3c-2d0b-4568-8bfa-339434cc7b5d.png)

**Comment by Taka152** [comment]
Have you installed ninja?

**Comment by Andrewlesson** [comment]
yes i have installed ninja, pip install lightseq, this command will to install ninja automatically

**Comment by Andrewlesson** [comment]
There are too many installation problems and It's too easy to make mistakes. Can you give me a Dockerfile ?  I believe many people will need it.

**Comment by Taka152** [comment]
OK, I'll consider adding a Dockerfile for a quick start.

**Comment by Taka152** [comment]
But for your problem, I suggest you check if PyTorch works fine, the error is raised from cpp_extension.

**Comment by HoyTta0** [comment]
Install PyTorch version with supported cuda will work.

**Comment by Andrewlesson** [comment]
> Install PyTorch version with supported cuda will work.

i try it again ,   but don't work,  could you give me a dockerfile ?

**Comment by Taka152** [comment]
You could find an image in [here](https://hub.docker.com/r/pytorch/pytorch/tags) with your working cuda and test pytorch works fine with GPU. Then you can try lightseq.

**Comment by Andrewlesson** [comment]
> You could find an image in [here](https://hub.docker.com/r/pytorch/pytorch/tags) with your working cuda and make sure pytorch works fine with GPU. Then you can try lightseq.

as you said. i use pytorch-image  pytorch:1.8.1-cuda10.2-cudnn7-runtime  successfully

**Comment by Taka152** [comment]
@Andrewlesson If you are running from source. Don't forget to run 'git submodule update --init'

**Comment by Andrewlesson** [comment]
> @Andrewlesson If you are running from source. Don't forget to run 'git submodule update --init'

According to what you said, the above problems did not appear, but new problems appeared. How to solve this problem?
![image](https://user-images.githubusercontent.com/10346684/145765663-21d202a8-0f8f-49a3-8e79-7b44d6b932dd.png)

**Comment by Taka152** [comment]
I think you should check if Fairseq can run successfully. And I suggest joining our Feishu group to reach us instantly, you can check this [doc](https://bytedance.feishu.cn/docs/doccn9w7UdOYcEOD99FjFVpdFzf#QSX6Bz).

**Comment by xs1997zju** [comment]
same problem

**Comment by etoilestar** [comment]
same problem, my Pytorch works fine.
