### ISSUE TITLE
The gridDim of ker_ln_bw_dgamma_dbetta is 'hidden_dim + TILE_DIM - 1' ?

### ISSUE THREAD

**Issue by butterluo** [bytedance/lightseq#233]
https://github.com/bytedance/lightseq/blob/51ef97a44d52ef77138fd453b34ff7eb6b492691/lightseq/training/csrc/kernels/normalize_kernels.cu#L512

It looks like '((hidden_dim + TILE_DIM - 1) / TILE_DIM) * TILE_DIM = (hidden_dim + TILE_DIM - 1)' ....
Is that what u want?
Or it should be gridDim = (hidden_dim + TILE_DIM - 1) / TILE_DIM ?

**Comment by neopro12** [comment]
Yes. It is what we want.
(hidden_dim + TILE_DIM - 1) / TILE_DIM is the number of thread warp.
e.g. hidden_dim=1023, tile_dim(warp_size)=32, then we get gridDim=1024

**Comment by butterluo** [comment]
If this is the case. In ur example, which hid_dim=1023 & grdDim=1024.
The blockIdx.x should be in [0,1023),  according to the line 'int idx = blockDim.x * blockIdx.x + threadIdx.x;' in ker_ln_bw_dgamma_dbetta(), the idx which used as the index of the 'betta' and 'gamma' will be in the range [0,32768], and it is much larger then the size of 'betta' and 'gamma' which is hid_dim according to ur comment.
And in this case,  after the blockIdx.x > 32, the idx will be larger then the variable 'width' which is hid_dim, then the program will never run into the code block of 'if (idx < width) {...}', that means there are 1024-32=992 thread blocks are useless.
Is that right? Or am I miss something? @neopro12

**Comment by neopro12** [comment]
I confirmed the number of blockDim and gridDim here: https://github.com/bytedance/lightseq/blob/51ef97a44d52ef77138fd453b34ff7eb6b492691/lightseq/training/csrc/kernels/normalize_kernels.cu#L183 
You're right. gridDim = (hidden_dim + TILE_DIM - 1) / TILE_DIM. So there are redundant blocks in: https://github.com/bytedance/lightseq/blob/51ef97a44d52ef77138fd453b34ff7eb6b492691/lightseq/training/csrc/kernels/normalize_kernels.cu#L512
Thanks, we will fix this bug. However, the performance loss here is very weak, so you can use the current version in the short term

**Comment by butterluo** [comment]
> I confirmed the number of blockDim and gridDim here:
> 
> https://github.com/bytedance/lightseq/blob/51ef97a44d52ef77138fd453b34ff7eb6b492691/lightseq/training/csrc/kernels/normalize_kernels.cu#L183
> 
> 
> You're right. gridDim = (hidden_dim + TILE_DIM - 1) / TILE_DIM. So there are redundant blocks in:
> https://github.com/bytedance/lightseq/blob/51ef97a44d52ef77138fd453b34ff7eb6b492691/lightseq/training/csrc/kernels/normalize_kernels.cu#L512
> 
> 
> Thanks, we will fix this bug. However, the performance loss here is very weak, so you can use the current version in the short term

You are welcome :)
