### ISSUE TITLE
which version of triton does lightseq can run in?

### ISSUE THREAD

**Issue by butterluo** [bytedance/lightseq#238]
which version of triton does lightseq can run in?

**Comment by neopro12** [comment]
The current version is v1.2.0 https://github.com/triton-inference-server/server/tree/v1.2.0
This version is a bit old and we will upgrade in the near future.
You can also try it like https://github.com/bytedance/lightseq/blob/master/lightseq/inference/server/transformer_server.cc.cu

**Comment by butterluo** [comment]
> The current version is v1.2.0 https://github.com/triton-inference-server/server/tree/v1.2.0 This version is a bit old and we will upgrade in the near future. You can also try it like https://github.com/bytedance/lightseq/blob/master/lightseq/inference/server/transformer_server.cc.cu

When will u upgrade the version of triton ? Is there any plan?

**Comment by neopro12** [comment]
In the next two months

**Comment by butterluo** [comment]
> In the next two months

Thx
