### ISSUE TITLE
RuntimeError: [CUDA][ERROR] /tmp/build-via-sdist-0g6f3d0w/lightseq-2.2.1/lightseq/inference/model/gpt_encoder.cc.cu(397): CUBLAS_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by TrLOX** [bytedance/lightseq#241]
I try to test gpt  in colab.
I got the runtimeErro below

!python /content/lightseq/examples/inference/python/test/ls_gpt2.py

initializing gpt tokenizer...
lightseq tokenizer pad token id: 50257
huggingface tokenizer pad token id: 50256
creating lightseq model...
Parsing hdf5: lightseq_gpt2_base.hdf5
loading 147 MB of embedding weight.
finish initializing emb_wei from host to device
loading 324 MB of encoder weight.
finish initializing enc_wei from host to device
Finish loading all weight from host to device
Allocated 105MB GPU buffer for GPT2
creating huggingface model...
====================START warmup====================
=========lightseq=========
lightseq generating...
Traceback (most recent call last):
  File "/content/lightseq/examples/inference/python/test/ls_gpt2.py", line 119, in <module>
    main()
  File "/content/lightseq/examples/inference/python/test/ls_gpt2.py", line 95, in main
    warmup(ls_tokenizer, hf_tokenizer, ls_model, hf_model, sentences)
  File "/content/lightseq/examples/inference/python/test/ls_gpt2.py", line 57, in warmup
    ls_generate(ls_model, ls_tokenizer, ls_inputs)
  File "/content/lightseq/examples/inference/python/test/ls_gpt2.py", line 34, in ls_generate
    ls_res_ids, ls_time = ls_gpt2(model, inputs)
  File "/content/lightseq/examples/inference/python/test/ls_gpt2.py", line 13, in ls_gpt2
    generated_ids = model.sample(inputs)
RuntimeError: [CUDA][ERROR] /tmp/build-via-sdist-0g6f3d0w/lightseq-2.2.1/lightseq/inference/model/gpt_encoder.cc.cu(397): CUBLAS_STATUS_ARCH_MISMATCH

**Comment by neopro12** [comment]
It may be caused by the low version of GPU Compute Capability. 
LightSeq supports GPU with Compute Capability equal or greater than 6.0.
You can checkout here to look up your GPU Compute Capability: https://developer.nvidia.com/cuda-gpus#compute
