### ISSUE TITLE
what about the vocab.txt of gpt2? Is it the same as bert 21128 words?

### ISSUE THREAD

**Issue by YINGPENGZH** [bytedance/lightseq#244]
The follwing code is official example. Is there a vocab.txt in lightseq?  The pad_id is [PAD]?   In bert, the id of "[PAD]" is zero, why pad_id = 50257 ? I am a lit bit confused.  what's the id eos_id?

if __name__ == "__main__":
    output_lightseq_model_name = "lightseq_gpt2_base"  # or "lightseq_gpt2_large"
    input_huggingface_gpt_model = "gpt2"  # or "gpt2-large"
    head_number = 12  # 20 for "gpt2-large"
    # generation_method should be "topk" or "topp"
    generation_method = "topk"
    topk = 1
    topp = 0.75
    **eos_id = 50256**
    **pad_id = 50257**
    max_step = 50
    extract_gpt_weights(
        output_lightseq_model_name,
        input_huggingface_gpt_model,
        head_num=head_number,  # layer number
        generation_method=generation_method,
        topk=topk,
        topp=topp,
        eos_id=eos_id,
        pad_id=pad_id,
        max_step=max_step,
    )

**Comment by neopro12** [comment]
You can set the value of [pad]/[bos]/[eos] arbitrarily, as long as it is consistent with your training process.

**Comment by neopro12** [comment]
Different models may have different vocabularies
