### ISSUE TITLE
Questions about gpu driver version

### ISSUE THREAD

**Issue by johnny-richards** [bytedance/lightseq#26]
Hi there, this is a really nice library for inference. However, we encountered the following problem of insufficient CUDA driver version while we attempted to load the model file. Here are the logs:
**model = lightseq.Transformer("lightseq_bart_base.pb", 128)
RuntimeError: [CUDA][ERROR] /workspace/pywrapper/transformer.cc.cu(43): CUDA driver version is insufficient for CUDA runtime version**
Where we found that such library has a painfully high requirement of devices.
Is it possible for you to support wider version of device and driver situations for different environment.
Thank you very much!
Regards!

**Comment by Taka152** [comment]
Sure, could you share your driver version, and we'll try to fix this problem.

**Comment by Taka152** [comment]
@johnny-richards You can try a lower version of CUDA to support older driver versions, 10.1 is used by lightseq, you can modify [here](https://github.com/bytedance/lightseq/blob/c1d0a9e355ffda4c8c8a67b224f5e85dfeea5117/CMakeLists.txt#L5) to support your driver.
![image](https://user-images.githubusercontent.com/18254977/115192794-dbe0d300-a11d-11eb-96f1-6f202bd46ac0.png)
> https://docs.nvidia.com/deploy/cuda-compatibility/index.html
