### ISSUE TITLE
Question about `token_type_embedding` 

### ISSUE THREAD

**Issue by zyds** [bytedance/lightseq#265]
Hi! I found that when the model was exported, `token_embedding` and `token_type_embedding` were combined together,

So how to deal with QA and sentence pair questions ?

**Comment by Taka152** [comment]
Good question, that's a feature missing in lightseq now, the bert encoder is simply reused from transformer encoder, we haven't implemented token_type_embedding currently.

**Comment by zyds** [comment]
> Good question, that's a feature missing in lightseq now, the bert encoder is simply reused from transformer encoder, we haven't implemented token_type_embedding currently.

Thanks for you reply!
