### ISSUE TITLE
from lightseq.training import export_pb2hdf5

### ISSUE THREAD

**Issue by Shijihao** [bytedance/lightseq#311]
I met a problem. I install lightseq==2.2.1, when I run "python hf_bart_export.py", There is an importError, cannot import name 'export_pb2hdf5'

The file address is "/export/util.py", line 6
from lightseq.training import export_pb2hdf5

**Comment by ifromeast** [comment]
@Shijihao 你好，请问cannot import name 'export_pb2hdf5' 的问题你解决了么
