### ISSUE TITLE
编译lightseq2.2.0版本，运行gpt2-large 例子报错

### ISSUE THREAD

**Issue by BucherLi** [bytedance/lightseq#314]
步骤一：在cuda 10.1 环境手动编译lightseq v2.2.0成功
![image](https://user-images.githubusercontent.com/12195338/170851603-cd4254c4-631b-4913-ab22-927db3d02ef2.png)

步骤二：导出gpt2 large模型到hdf5格式成功
python3 export/hf_gpt2_export.py
![image](https://user-images.githubusercontent.com/12195338/170851868-baacc223-ffc6-4457-906c-4def8a2c923c.png)

步骤三：执行gpt2 预测demo失败
报错信息：
`Parsing hdf5: lightseq_gpt2_large.hdf5
loading 245 MB of embedding weight.
finish initializing emb_wei from host to device
loading 2702 MB of encoder weight.
finish initializing enc_wei from host to device
Finish loading all weight from host to device
Allocated 164MB GPU buffer for GPT2
batch_size-5 batch_seq_len-3
Sample with topk
padding_id: 50257
vocab_size: 50257
batch_token_ids: 40, 1842, 3555, 40, 1842, 3555, 40, 1842, 3555, 40, 1842, 3555, 40, 1842, 3555, 
embedding: Traceback (most recent call last):
  File "test.py", line 17, in <module>
    topk=4,
RuntimeError: parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument`

运行代码：
`
import lightseq.inference as lsi
import time
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

tokenizer.pad_token = tokenizer.eos_token
model = lsi.Gpt("lightseq_gpt2_large.hdf5", max_batch_size=6)
sentences = ["I love reading", "I love reading","I love reading", "I love reading", "I love reading"]
inputs = tokenizer(sentences, return_tensors="pt", padding=True)[
    "input_ids"
]
#模型推断开始
start_time = time.perf_counter()
generated_ids = model.sample(
    inputs,
    topk=4,
    # topp=0.2,
)
print(generated_ids)
#模型推断结束
end_time = time.perf_counter()

result = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

print("="*88)
print(f"result: {result}")
print(f"inference time: {end_time-start_time} s")
`

**Comment by neopro12** [comment]
1. Can you try a smaller model to verify that it's an oom problem
2. Is the input ids out of vocabulary size?

**Comment by BucherLi** [comment]
> 

i try it again，i find its ok when building with “PATH=/usr/local/hdf5/:$PATH NABLE_FP32=1  pip3 install -e ..” .
but it report wrong when building with "PATH=/usr/local/hdf5/:$PATH ENABLE_FP32=1 ENABLE_DEBUG=1  pip3 install -e .."

**Comment by Taka152** [comment]
You can add `-v` like `... pip3 install -e . -v` to see if lightseq.inference is built successfully.
