### ISSUE TITLE
[CUDA][ERROR]: misaligned address

### ISSUE THREAD

**Issue by fc20567** [bytedance/lightseq#329]
hi, I have 1 question.  When a large amount of text requests the model, the model starts to run properly. After the model runs for a period of time, the program reports an error :  [CUDA][ERROR] /tmp/build-via-sdist-uagdfpbf/lightseq-2.2.1/lightseq/inference/pywrapper/gpt.cc.cu(160): misaligned address.

**Comment by hexisyztem** [comment]
What is the run command you executed.

**Comment by hexisyztem** [comment]
I guess that your input request is too large, in this case it is recommended to use tritonserver to schedule requests.

**Comment by fc20567** [comment]
> What is the run command you executed.
![cuda_error](https://user-images.githubusercontent.com/26130068/175504367-cccbf4ab-afaf-4aa9-8956-e141e8794f32.PNG)

**Comment by fc20567** [comment]
> I guess that your input request is too large, in this case it is recommended to use tritonserver to schedule requests.

The test code has been posted. Is this the error caused by large requests?  thank you.

**Comment by hexisyztem** [comment]
Sorry, I missed your email message over the weekend. 
You can try to run the input statement that reports the error once alone for further judgment.

**Comment by fc20567** [comment]
> Sorry, I missed your email message over the weekend. You can try to run the input statement that reports the error once alone for further judgment.
Thx，problem has solved.  input data have "-" symbol, cause model.sample() throw an exception.
