### ISSUE TITLE
是否支持huggingface T5ForConditionalGenerartion的加速

### ISSUE THREAD

**Issue by czq1999** [bytedance/lightseq#351]

**Comment by anaivebird** [comment]
https://github.com/bytedance/lightseq/tree/t5_support
这个分支上有，还没merge到master

**Comment by anaivebird** [comment]
导出可以用t5_support分支的lightseq/examples/inference/python/export/huggingface/hf_t5_export.py

推理用：lightseq/examples/inference/python/test/ls_t5.py

**Comment by anaivebird** [comment]
master分支已支持
