### ISSUE TITLE
Setting sampling method as topk=8, there are more than 8 different values of first token with same input.

### ISSUE THREAD

**Issue by Majokiki** [bytedance/lightseq#36]
Hello, thank you very much for your help!

The experimental condition is：

- set the sampling method of the lightseq GPT model to topk=8
- keep the same input and generate 30 times repeatedly, and then remove the duplicates after 30 sentences are obtained.

It is found that there are more than 8 different values of first token in the sentences generated by the repeated experiment. 

P.S.  `\[\w+\]` in the picture are words in vocab.txt.

![image](https://user-images.githubusercontent.com/37956548/116379842-fca7d780-a845-11eb-861b-3504174f9f0a.png)

**Comment by Taka152** [comment]
@Majokiki the top-k method returns the approximate top-k results for performance reason, you can check [here](https://github.com/bytedance/lightseq/blob/c1d0a9e355ffda4c8c8a67b224f5e85dfeea5117/kernels/gptKernels.cc.cu#L512)

**Comment by Majokiki** [comment]
I thought it were the accurate top-k results based on this line in the blog 🙈. 

![image #50%](https://user-images.githubusercontent.com/37956548/116492723-923b7980-a8cf-11eb-9ac1-36adb073f543.png)


Why don’t we go just one step further and get the accurate top-k from the approximate results？

I also tried topk=4 and  found more than 8 kinds of results🙈 

![image](https://user-images.githubusercontent.com/37956548/116493843-23135480-a8d2-11eb-96aa-0a69c47eb286.png)

Thanks a lot！

**Comment by Taka152** [comment]
it is accurate in beam search, just in the sampling methods, we decide to
trade accuracy for performance because the randomization of sampling

Majokiki ***@***.***> 于2021年4月29日周四 上午10:13写道：

**Comment by Taka152** [comment]
And you're welcome to create a pr if you're interested😉, the approximate version works fine in our applications.

**Comment by Majokiki** [comment]
🥰 thanks，I'll try it on the coming holiday
