### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by zhuyan111** [bytedance/lightseq#371]
I had this problem when I distributed training: 
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
![image](https://user-images.githubusercontent.com/59304463/187675804-337ff5e9-ea5e-4152-a972-28e039898ee7.png)

**Comment by Hobbite** [comment]
I meet the same problem. It works well when using small trainning dataset, which could successfully save chekpoint. While using large tranning dataset, the problem happens. How did solve it?

**Comment by Taka152** [comment]
Could you share more context?
