### ISSUE TITLE
What is the purpose of layers_new?

### ISSUE THREAD

**Issue by melody-rain** [bytedance/lightseq#375]

**Comment by hexisyztem** [comment]
We refactored the architecture logic of lightseq to make memory multiplexing between tensors an automatic process without the need to manually specify the specific address of the tensor. layer_new is an intermediate product of the migration process, and we will eventually fully convert to the new version of the architecture, and the upper-layer logic is unaware of it.

**Comment by hexisyztem** [comment]
After completing the architecture migration, we will summarize and organize this part of the technology into documents. If you are interested in this part of the content, you can pay attention to the subsequent version releases

**Comment by melody-rain** [comment]
Thanks for your kind reply.
