### ISSUE TITLE
to run quant train, which cuda version should use?

### ISSUE THREAD

**Issue by tricky61** [bytedance/lightseq#381]
the stable v2.2.0 has no lightseq.training.ops.pytorch.quantization, so just build from the newest master code, right?
I use the cuda-11.5 and build from source. since cmake error message "missing CUDA::cublas_static", I set DYNAMIC_API ON.
when running the quant train, it stoped with the message "RuntimeError: [CUDA][ERROR] /home/data/quant/lightseq/lightseq/csrc/kernels/cublas_wrappers.cpp(164): CUBLAS_STATUS_NOT_SUPPORTED" . 
Any one can tell me how to solve the problem?

**Comment by Taka152** [comment]
Which GPU are you using?

**Comment by tricky61** [comment]
> 

Tesla V100-SXM2

**Comment by tricky61** [comment]
> Which GPU are you using?
By the way, there are running warnings bellow, does the error have relation with the warning? I cannot find this file in my system.
[WARNING] /tmp/igemm_configs/igemm_sm80.cfg is not found; using default GEMM algo

**Comment by Taka152** [comment]
The recently released quant training of lightseq layers only supports A100 or compute capability greater than 80, because it uses real int8 gemm instead of fake quantization. If you are using V100, you can use torch layers to try quant training and lightseq accelerated quant inferences on other GPU support int8.

**Comment by tricky61** [comment]
> The recently released quant training of lightseq layers only supports A100 or compute capability greater than 80, because it uses real int8 gemm instead of fake quantization. If you are using V100, you can use torch layers to try quant training and lightseq accelerated quant inferences on other GPU support int8.

I get it.
thanks very much.
