### ISSUE TITLE
'Namespace' object has no attribute 'enable_GCQ' with lightseq 3.0.0 

### ISSUE THREAD

**Issue by stephanpeitz** [bytedance/lightseq#405]
Hi all,

I just updated to lightseq version 3.0.0 and now run into following error:

```
File "/miniconda/lib/python3.7/site-packages/lightseq/training/gcq/ls_fs_gcq_trainer.py", line 29, in model
and self.args.enable_GCQ
AttributeError: 'Namespace' object has no attribute 'enable_GCQ'
```

I reverted back to version 2.2.1 which solves the issue.

Cheers,
Stephan

**Comment by Taka152** [comment]
Hi Stephan, 

Thanks for your feedback, we will check the GCQ example and fix it.

Cheers, 
Ying

**Comment by Taka152** [comment]
@stephanpeitz Did you test on fairseq==0.10.2?

**Comment by stephanpeitz** [comment]
No, I'm on 0.10.1.

**Comment by Taka152** [comment]
we have made a hotfix for a possible compatible issue, could you try our latest master to see if this problem still exists?

**Comment by stephanpeitz** [comment]
It works! Thanks for quick fix!
