### ISSUE TITLE
add huggingface gpt2 or t5 export example?

### ISSUE THREAD

**Issue by gyin-ai** [bytedance/lightseq#42]
can I ask whether we can add huggingface gpt2 or t5 example in lightseq? Since they are the most frequently downloaded and used models in huggingface.

**Comment by Taka152** [comment]
@gyin-ai Yes, model downloads is a really good metric, we're considering adding example for Bert, GPT2, and T5, they are expected to be supported this two months, stay tuned.

**Comment by gyin-ai** [comment]
Thanks. Here is the download ranking `https://huggingface.co/models`.  Bert, GPT2 and T5 are indeed top 3 models.

**Comment by anaivebird** [comment]
T5 has been supported on master branch
