### ISSUE TITLE
add lightseq implementation as a tf customized op?

### ISSUE THREAD

**Issue by gyin-ai** [bytedance/lightseq#43]
fastertransformer creates a tf op wrapper for its implementation. So that it can be easily imported into tf for usage. Any plan to add this for lightseq as well?
1. https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/tf_op/gpt_op.cc

2.https://github.com/NVIDIA/FasterTransformer/blob/93b7751bcbb4b7b29ce647b646baa6414790d4d0/sample/tensorflow/gpt_sample.py#L307

**Comment by Taka152** [comment]
python wrapper could be used in both tensorflow and pytorch, but now only transformer is supported, we will support more models in the future.

**Comment by gyin-ai** [comment]
this is different from python wrapper. Basically if the tf op wrapper is created, users can export it into as a standard tf saved model and use anywhere like tfserving.
https://www.tensorflow.org/guide/create_op

**Comment by gyin-ai** [comment]
@Taka152 can I ask whether the team has used triton in production for lightseq?

**Comment by Taka152** [comment]
YES, we have used  both triton and python wrapper in the production


gyin-ai ***@***.***> 于2021年5月21日周五 上午12:04写道：
