### ISSUE TITLE
是否考虑支持T5/GPT2模型？

### ISSUE THREAD

**Issue by zmingshi** [bytedance/lightseq#44]
您好：
      感谢开源，试用了下lightseq, 感觉效果还是非常惊人的，提速10倍左右。
      生成模型领域较好的T5/GPT2是否也有考虑支持呢？有具体时间计划吗？

**Comment by Taka152** [comment]
#42 we are working on it, gpt2 example is expected to be released this month.

**Comment by gyin-ai** [comment]
@Taka152 I saw the latest gpt2 example commit was merged. But the wheel version also needs to be updated to support it. I have a question where we can set `_max_step` (something similar to extra_decode_length) for gpt2 in protobuf?

**Comment by zmingshi** [comment]
> #42 we are working on it, gpt2 example is expected to be released this month.

感谢！非常期待！

**Comment by NLPIG** [comment]
> #42 we are working on it, gpt2 example is expected to be released this month.

能否把GPT2-ML也支持一下 (/^▽^)/

**Comment by Taka152** [comment]
Actually, we have already supported it.
The GPT example will be updated to show the usage of compute ppl

NLPIG ***@***.***> 于2021年6月24日周四 下午8:04写道：

**Comment by anaivebird** [comment]
master分支T5已支持
