### ISSUE TITLE
请问对于LSTM的量化，有用cuBLASLt库实现的方案吗？

### ISSUE THREAD

**Issue by piaohe20221128** [bytedance/lightseq#449]
在代码中看到对于LSTM用的是传统的量化方法，即用的float的GEMM计算的，请问有没有用int8 GEMM计算的方案呢？非常感谢！！！

**Comment by neopro12** [comment]
Currently LSTM models are not supported. For Transformer models, we use cuBLASLt for int8 GEMM.

**Comment by piaohe20221128** [comment]
thank you
