### ISSUE TITLE
how do we control the fp16 vs fp32 mode in Python API example?

### ISSUE THREAD

**Issue by gyin-ai** [bytedance/lightseq#48]
how do we control the fp16 vs fp32 mode in Python API example? Thanks

**Comment by Taka152** [comment]
@gyin-ai It needs to add `ENABLE_FP32` env when build by setup.py to switch between fp16 and fp32. You can check `build_wheels.sh` and `docker/Dockerfile.pypi` to get insights. I will also consider supporting dynamic switch in the future.
