### ISSUE TITLE
cuda 11.3 already has cub,  will conflict with  3rdparty/cub/

### ISSUE THREAD

**Issue by ustcdane** [bytedance/lightseq#50]
cuda 11.3 already has cub in /usr/local/cuda/include/cub,  will conflict with  3rdparty/cub/
error:
usr/local/cuda/include/cub/block/../util_type.cuh(72): error: class template "cub::If" has already been defined
/usr/local/cuda/include/cub/block/../util_type.cuh(81): error: class template "cub::If" has already been defined
/usr/local/cuda/include/cub/block/../util_type.cuh(98): error: class template "cub::Equals" has already been defined
/usr/local/cuda/include/cub/block/../util_type.cuh(72): error: class template "cub::If" has already been defined
/usr/local/cuda/include/cub/block/../util_type.cuh(109): error: class template "cub::Equals" has already been defined
/usr/local/cuda/include/cub/block/../util_type.cuh(81): error: class template "cub::If" has already been defined

**Comment by Taka152** [comment]
@ustcdane That's indeed a problem that should be fixed in the future, for now, I recommend using older cuda to compile, and it could run on newer drivers.

**Comment by ustcdane** [comment]
@Taka152  Yes, using CUDA10.1 or CUDA10.2  is ok and it could run on  Driver Version: 465.19.01    CUDA Version: 11.3
