### ISSUE TITLE
ModuleNotFoundError: No module named 'lightseq.inference'; 'lightseq' is not a package

### ISSUE THREAD

**Issue by gm3g11** [bytedance/lightseq#59]
I could use the " pip install lightseq" command to install the lightseq package, and I could import the lightseq in the python file. But I encountered "ModuleNotFoundError: No module named 'lightseq.inference'; 'lightseq' is not a package" when I try to run the command "import lightseq.inference as lsi". Do I miss some steps? Thanks.

**Comment by Taka152** [comment]
@gm3g11 the master readme is updated to version 2.0.0，but pypi version is still 1.2，and we're updating it.For now,You can checkout the 1.2 tag and follow that readme.

**Comment by Taka152** [comment]
You can try it again, we have updated the pypi version to 2.0.0

**Comment by zmingshi** [comment]
> You can try it again, we have updated the pypi version to 2.0.0

I am faced with the same problem, 
I install from the source codes, like `python setup.py install`
```shell
lightseq                 2.0.0
```

the problem remains, 
```shell
$python ls_gpt_time_test.py
Traceback (most recent call last):
  File "ls_gpt_time_test.py", line 3, in <module>
    import lightseq.inference as lsi
ModuleNotFoundError: No module named 'lightseq.inference'
```

**Comment by Taka152** [comment]
@zmingshi install from source with inference support need to install cmake and protobuf, check `docs/build.md`, it will only install training module if inference installation failed, you can check warning log to verify it.

wheels on `https://pypi.tuna.tsinghua.edu.cn/simple/lightseq/` haven't synced to the latest version, you can try the default PyPI index.

**Comment by zmingshi** [comment]
> @zmingshi You can check `docs/build.md` to install from source with inference support. And it will only install the training module if inference installation failed, you can check the warning log to verify it.
> 
> wheels on `https://pypi.tuna.tsinghua.edu.cn/simple/lightseq/` haven't synced to the latest version, you can try the default PyPI index.

thanks a lot, installing from PyPI index  works fine now!
