### ISSUE TITLE
Is there any doc to help user build lightseq from source?

### ISSUE THREAD

**Issue by butterluo** [bytedance/lightseq#88]
Is there any doc to help user build lightseq from source?

**Comment by Taka152** [comment]
@butterluo I guess you want to build inference from source. Please check [here](https://github.com/bytedance/lightseq/blob/master/docs/inference/build.md)

**Comment by butterluo** [comment]
> @butterluo I guess you want to build inference from source. Please check [here](https://github.com/bytedance/lightseq/blob/master/docs/inference/build.md)

Thank you @Taka152 , what about the training part? Can it build from source?

**Comment by Taka152** [comment]
@butterluo training module will build at runtime.

**Comment by butterluo** [comment]
> @butterluo training module will build at runtime.

I c, it's an torch extention. Thank you!
