### ISSUE TITLE
How to profile "latency ratio of each module"?

### ISSUE THREAD

**Issue by wxyhv** [bytedance/lightseq#89]
![image](https://user-images.githubusercontent.com/19853092/124278718-32847780-db79-11eb-9aec-c5d7ce43ec22.png)
I found the "Delay ratio of each calculation module" picture in https://bytedance.feishu.cn/docs/doccnUJ5X9WWEdQxXwzbPJ581J0#.

I wonder which GPU profiler can generate the picture.
Thank you very much!

**Comment by Taka152** [comment]
Its based on nvprov results and our analysis。You can check nvprov and nsight system to profile gpu program.

**Comment by wxyhv** [comment]
OK, I think you mean nvprof, not nvprov. Thank you!
