### ISSUE TITLE
file to use the example in readme, plz help, thanks

### ISSUE THREAD

**Issue by 652994331** [bytedance/lightseq#9]
i download v1.0.0_libs and v0.0.1.gptlm.pkg and follow the readme instruction to start the server
![image](https://user-images.githubusercontent.com/51428350/97243017-936ddb80-17b2-11eb-8034-70141b31f59e.png)
i met this problem:
![image](https://user-images.githubusercontent.com/51428350/97243119-d7f97700-17b2-11eb-8ead-ad177b017a86.png)

could you please help, i pulled the docker follow the readme.

**Comment by Taka152** [comment]
The log at the last line informs out of GPU memory. You can adjust `max_batch_size: 1024` in `config.pbtxt` to a value (maybe 128) that suits your GPU memory. Lightseq will register GPU memory based on this parameter.
