### ISSUE TITLE
Should perform the 'div sqrt(d_k)' operator after Q*K

### ISSUE THREAD

**Issue by butterluo** [bytedance/lightseq#91]
https://github.com/bytedance/lightseq/blob/b900c5ad6ce32af4c9f64e0c9d969c008dc2e44b/lightseq/training/csrc/ops/transformer_encoder_layer.cpp#L76

I found that you haven't divide the 'sqrt(d_k) after Q*K and before softmax. It will cause some problem if input large number. especially in post layer-norm case. Is it a bug? Or did i miss some code which can perform the division?

**Comment by Taka152** [comment]
You can check here https://github.com/bytedance/lightseq/blob/b900c5ad6ce32af4c9f64e0c9d969c008dc2e44b/lightseq/training/csrc/ops/transformer_encoder_layer.cpp#L40-L42

**Comment by butterluo** [comment]
> You can check here
> 
> https://github.com/bytedance/lightseq/blob/b900c5ad6ce32af4c9f64e0c9d969c008dc2e44b/lightseq/training/csrc/ops/transformer_encoder_layer.cpp#L40-L42



> You can check here
> 
> https://github.com/bytedance/lightseq/blob/b900c5ad6ce32af4c9f64e0c9d969c008dc2e44b/lightseq/training/csrc/ops/transformer_encoder_layer.cpp#L40-L42

HA,HA, Good Design :)
