### ISSUE TITLE
When the completed HuggingFace transformers example will be released? (To demonstrate how to use the lightSeq implement of embed,encod,decod,heads etc. )

### ISSUE THREAD

**Issue by butterluo** [bytedance/lightseq#96]
Current HuggingFace example is only support the lightSeq implement of encode layer, it may not be enough for people's use case. When the completed HuggingFace transformers example will be released? (To demonstrate how to use the lightSeq implement of embed,encod,decod,heads etc. )

**Comment by Taka152** [comment]
Currently, We don't have plans to support Transformer in huggingface, because there is already fairseq example.
We are working on FP16 Bert example on huggingface, and after that, we will focus on in-house business and Tensorflow open source.

Other examples may be considered since September.
